// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpLI-00X6XL5ap4lUhFzDwioNftk4-gi8',
    appId: '1:749131221978:web:3132c400ef53b6c1df8ee3',
    messagingSenderId: '749131221978',
    projectId: 'co2307-cbeea',
    authDomain: 'co2307-cbeea.firebaseapp.com',
    storageBucket: 'co2307-cbeea.firebasestorage.app',
    measurementId: 'G-7R70ZRGVMT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUcntiPcdGGNF7VyMgrBbmEoxoTT2U7Kc',
    appId: '1:749131221978:android:4cb4dc27b9cc6e59df8ee3',
    messagingSenderId: '749131221978',
    projectId: 'co2307-cbeea',
    storageBucket: 'co2307-cbeea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGSBR0DNmJCObniwUyBsq8ha57Kp4kscs',
    appId: '1:749131221978:ios:9830bc3301f09dfedf8ee3',
    messagingSenderId: '749131221978',
    projectId: 'co2307-cbeea',
    storageBucket: 'co2307-cbeea.firebasestorage.app',
    androidClientId: '749131221978-9bolv12cksc44mun1lktcviao95kajo8.apps.googleusercontent.com',
    iosClientId: '749131221978-5q1cp6greo34qhp367aqfvm1j97tt182.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackMyBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGSBR0DNmJCObniwUyBsq8ha57Kp4kscs',
    appId: '1:749131221978:ios:9830bc3301f09dfedf8ee3',
    messagingSenderId: '749131221978',
    projectId: 'co2307-cbeea',
    storageBucket: 'co2307-cbeea.firebasestorage.app',
    androidClientId: '749131221978-9bolv12cksc44mun1lktcviao95kajo8.apps.googleusercontent.com',
    iosClientId: '749131221978-5q1cp6greo34qhp367aqfvm1j97tt182.apps.googleusercontent.com',
    iosBundleId: 'com.example.trackMyBus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpLI-00X6XL5ap4lUhFzDwioNftk4-gi8',
    appId: '1:749131221978:web:27c1aaaa1912d003df8ee3',
    messagingSenderId: '749131221978',
    projectId: 'co2307-cbeea',
    authDomain: 'co2307-cbeea.firebaseapp.com',
    storageBucket: 'co2307-cbeea.firebasestorage.app',
    measurementId: 'G-CJ4NQKBTPM',
  );

}